### ISSUE TITLE
Error running a follower node

### ISSUE THREAD

**Issue by radicleart** [hirosystems/docs#221]
Following this guide: https://docs.hiro.so/get-started/running-mainnet-node#step-2-running-stacks-blockchain leads the following stack trace..

```$:~/hubgit/stacks-node$ docker run --rm   --name stacks-blockchain   -v $(pwd)/persistent-data/stacks-blockchain/mainnet:/root/stacks-node/data   -v $(pwd)/config/mainnet:/src/stacks-node   -p 20443:20443   -p 20444:20444   blockstack/stacks-blockchain /bin/stacks-node start --config /src/stacks-node/Config.toml
INFO [1668348750.101193] [testnet/stacks-node/src/main.rs:80] [main] stacks-node 2.05.0.1.0 (master:de541f9, release build, linux [x86_64])
INFO [1668348750.101253] [testnet/stacks-node/src/main.rs:113] [main] Loading config at path /src/stacks-node/Config.toml
Process abort due to thread panic: panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', testnet/stacks-node/src/config.rs:107:52
   0: stacks_node::main::{{closure}}
             at src/testnet/stacks-node/src/main.rs:57:18
   1: std::panicking::rust_panic_with_hook
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   6: core::result::unwrap_failed
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   7: core::result::Result<T,E>::unwrap
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
      stacks_node::config::ConfigFile::from_path
             at src/testnet/stacks-node/src/config.rs:107:27
   8: stacks_node::main
             at src/testnet/stacks-node/src/main.rs:114:13
   9: core::ops::function::FnOnce::call_once
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:123:18
  10: std::rt::lang_start::{{closure}}
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:145:18
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
      std::panicking::try
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal::{{closure}}
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
      std::panicking::try
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal
             at rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  12: main

Dumping core for pid 1```

**Comment by radicleart** [comment]
Looks like its just a bug in the doc

`First, create the ./config/Config.toml file and add the following`

should be move it to ./config/mainnet/Config.toml

**Comment by LakshmiLavanyaKasturi** [comment]
Thanks, @radicleart. I will update the doc.
